name: CI Test

on:
  push:
    branches:
      - ci
  workflow_dispatch:
    inputs:
      version:
        description: 'Release tag name (default libdovi version)'
        default: ''

jobs:
  build:
    permissions:
      contents: write
    uses: mpvkit/BuildShared/.github/workflows/build.yml@a8f5d9977128f0ec66d3f8d6ec5dbd42598aa67c
    secrets: inherit
    with:
      version: '${{ github.event.inputs.version }}'
      library: 'libdovi'
      try_run: true
